# Generated by Django 4.2.24 on 2025-09-11 16:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Unique bank account number', max_length=20, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance for operations', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('PEN', 'Soles Peruanos'), ('USD', 'Dólares Americanos'), ('EUR', 'Euros')], default='PEN', help_text='Account currency', max_length=3)),
                ('opening_date', models.DateTimeField(auto_now_add=True, help_text='Account opening date')),
                ('last_movement_date', models.DateTimeField(blank=True, help_text='Date of last transaction', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('BLOCKED', 'Bloqueada'), ('CLOSED', 'Cerrada')], default='ACTIVE', help_text='Current account status', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version for change control')),
                ('customer', models.ForeignKey(help_text='Account owner customer', on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Cuenta de Ahorro',
                'verbose_name_plural': 'Cuentas de Ahorro',
                'db_table': 'savings_accounts',
                'indexes': [models.Index(fields=['account_number'], name='idx_account_number'), models.Index(fields=['customer'], name='idx_account_customer'), models.Index(fields=['status'], name='idx_account_status'), models.Index(fields=['opening_date'], name='idx_account_opening_date')],
            },
        ),
    ]
