# Generated by Django 4.2.24 on 2025-09-11 17:15

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique transaction reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Depósito"),
                            ("WITHDRAWAL", "Retiro"),
                            ("TRANSFER_OUT", "Transferencia Salida"),
                            ("TRANSFER_IN", "Transferencia Entrada"),
                        ],
                        help_text="Type of transaction",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PEN", "Soles Peruanos"),
                            ("USD", "Dólares Americanos"),
                            ("EUR", "Euros"),
                        ],
                        default="PEN",
                        help_text="Transaction currency",
                        max_length=3,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Transaction description", max_length=500
                    ),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Balance before transaction",
                        max_digits=15,
                    ),
                ),
                (
                    "new_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Balance after transaction",
                        max_digits=15,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Transaction creation date"
                    ),
                ),
                (
                    "processing_date",
                    models.DateTimeField(
                        blank=True, help_text="Transaction processing date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSED", "Procesada"),
                            ("REJECTED", "Rechazada"),
                            ("REVERSED", "Reversada"),
                        ],
                        default="PENDING",
                        help_text="Transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="IP address of origin"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent information", max_length=500
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination account (only for transfers)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="accounts.savingsaccount",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        help_text="Source account for the transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="accounts.savingsaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who executed the transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["reference_number"], name="idx_transaction_reference"
                    ),
                    models.Index(
                        fields=["source_account"], name="idx_transaction_source"
                    ),
                    models.Index(
                        fields=["transaction_date"], name="idx_transaction_date"
                    ),
                    models.Index(fields=["status"], name="idx_transaction_status"),
                    models.Index(
                        fields=["transaction_type"], name="idx_transaction_type"
                    ),
                ],
            },
        ),
    ]
