# Generated by Django 4.2.24 on 2025-09-11 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_table', models.CharField(help_text='Name of the affected database table', max_length=50)),
                ('record_id', models.BigIntegerField(help_text='ID of the affected record')),
                ('operation', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], help_text='Type of database operation performed', max_length=10)),
                ('previous_data', models.JSONField(blank=True, help_text='Previous data before the operation (JSON format)', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='New data after the operation (JSON format)', null=True)),
                ('operation_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the operation was performed')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the operation was performed')),
                ('user_agent', models.CharField(blank=True, help_text='User agent information from the request', max_length=500)),
                ('context', models.CharField(blank=True, help_text="Additional context about the operation (e.g., 'admin_panel', 'api_rest')", max_length=100)),
                ('user', models.ForeignKey(help_text='User who performed the operation', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'audit',
                'ordering': ['-operation_date'],
                'indexes': [models.Index(fields=['affected_table', 'record_id'], name='idx_audit_table_record'), models.Index(fields=['user'], name='idx_audit_user'), models.Index(fields=['operation_date'], name='idx_audit_date'), models.Index(fields=['operation'], name='idx_audit_operation'), models.Index(fields=['affected_table'], name='idx_audit_table')],
            },
        ),
    ]
